//! Vulkan 1.2 Core Structures and Functions

const types = @import("types.zig");
const constants = @import("constants.zig");

// ============================================================================
// Structures
// ============================================================================

pub const PhysicalDeviceVulkan11Features = extern struct {
    s_type: types.StructureType = .physical_device_vulkan_1_1_features,
    p_next: ?*anyopaque = null,
    storage_buffer_16_bit_access: types.Bool32,
    uniform_and_storage_buffer_16_bit_access: types.Bool32,
    storage_push_constant_16_bit: types.Bool32,
    storage_input_output_16_bit: types.Bool32,
    multiview: types.Bool32,
    multiview_geometry_shader: types.Bool32,
    multiview_tessellation_shader: types.Bool32,
    variable_pointers: types.Bool32,
    variable_pointers_storage_buffer: types.Bool32,
    protected_memory: types.Bool32,
    sampler_ycbcr_conversion: types.Bool32,
    shader_draw_parameters: types.Bool32,
};

pub const PhysicalDeviceVulkan11Properties = extern struct {
    s_type: types.StructureType = .physical_device_vulkan_1_1_properties,
    p_next: ?*anyopaque = null,
    device_uuid: [constants.UUID_SIZE]u8,
    driver_uuid: [constants.UUID_SIZE]u8,
    device_luid: [constants.LUID_SIZE]u8,
    device_node_mask: u32,
    device_luid_valid: types.Bool32,
    subgroup_size: u32,
    subgroup_supported_stages: types.ShaderStageFlags,
    subgroup_supported_operations: types.SubgroupFeatureFlags,
    subgroup_quad_operations_in_all_stages: types.Bool32,
    point_clipping_behavior: types.PointClippingBehavior,
    max_multiview_view_count: u32,
    max_multiview_instance_index: u32,
    protected_no_fault: types.Bool32,
    max_per_set_descriptors: u32,
    max_memory_allocation_size: types.DeviceSize,
};

pub const PhysicalDeviceVulkan12Features = extern struct {
    s_type: types.StructureType = .physical_device_vulkan_1_2_features,
    p_next: ?*anyopaque = null,
    sampler_mirror_clamp_to_edge: types.Bool32,
    draw_indirect_count: types.Bool32,
    storage_buffer_8_bit_access: types.Bool32,
    uniform_and_storage_buffer_8_bit_access: types.Bool32,
    storage_push_constant_8_bit: types.Bool32,
    shader_buffer_int64_atomics: types.Bool32,
    shader_shared_int64_atomics: types.Bool32,
    shader_float16: types.Bool32,
    shader_int8: types.Bool32,
    descriptor_indexing: types.Bool32,
    shader_input_attachment_array_dynamic_indexing: types.Bool32,
    shader_uniform_texel_buffer_array_dynamic_indexing: types.Bool32,
    shader_storage_texel_buffer_array_dynamic_indexing: types.Bool32,
    shader_uniform_buffer_array_non_uniform_indexing: types.Bool32,
    shader_sampled_image_array_non_uniform_indexing: types.Bool32,
    shader_storage_buffer_array_non_uniform_indexing: types.Bool32,
    shader_storage_image_array_non_uniform_indexing: types.Bool32,
    shader_input_attachment_array_non_uniform_indexing: types.Bool32,
    shader_uniform_texel_buffer_array_non_uniform_indexing: types.Bool32,
    shader_storage_texel_buffer_array_non_uniform_indexing: types.Bool32,
    descriptor_binding_uniform_buffer_update_after_bind: types.Bool32,
    descriptor_binding_sampled_image_update_after_bind: types.Bool32,
    descriptor_binding_storage_image_update_after_bind: types.Bool32,
    descriptor_binding_storage_buffer_update_after_bind: types.Bool32,
    descriptor_binding_uniform_texel_buffer_update_after_bind: types.Bool32,
    descriptor_binding_storage_texel_buffer_update_after_bind: types.Bool32,
    descriptor_binding_update_unused_while_pending: types.Bool32,
    descriptor_binding_partially_bound: types.Bool32,
    descriptor_binding_variable_descriptor_count: types.Bool32,
    runtime_descriptor_array: types.Bool32,
    sampler_filter_minmax: types.Bool32,
    scalar_block_layout: types.Bool32,
    imageless_framebuffer: types.Bool32,
    uniform_buffer_standard_layout: types.Bool32,
    shader_subgroup_extended_types: types.Bool32,
    separate_depth_stencil_layouts: types.Bool32,
    host_query_reset: types.Bool32,
    timeline_semaphore: types.Bool32,
    buffer_device_address: types.Bool32,
    buffer_device_address_capture_replay: types.Bool32,
    buffer_device_address_multi_device: types.Bool32,
    vulkan_memory_model: types.Bool32,
    vulkan_memory_model_device_scope: types.Bool32,
    vulkan_memory_model_availability_visibility_chains: types.Bool32,
    shader_output_viewport_index: types.Bool32,
    shader_output_layer: types.Bool32,
    subgroup_broadcast_dynamic_id: types.Bool32,
};

pub const PhysicalDeviceVulkan12Properties = extern struct {
    s_type: types.StructureType = .physical_device_vulkan_1_2_properties,
    p_next: ?*anyopaque = null,
    driver_id: types.DriverId,
    driver_name: [constants.MAX_DRIVER_NAME_SIZE]u8,
    driver_info: [constants.MAX_DRIVER_INFO_SIZE]u8,
    conformance_version: types.ConformanceVersion,
    denorm_behavior_independence: types.ShaderFloatControlsIndependence,
    rounding_mode_independence: types.ShaderFloatControlsIndependence,
    shader_signed_zero_inf_nan_preserve_float16: types.Bool32,
    shader_signed_zero_inf_nan_preserve_float32: types.Bool32,
    shader_signed_zero_inf_nan_preserve_float64: types.Bool32,
    shader_denorm_preserve_float16: types.Bool32,
    shader_denorm_preserve_float32: types.Bool32,
    shader_denorm_preserve_float64: types.Bool32,
    shader_denorm_flush_to_zero_float16: types.Bool32,
    shader_denorm_flush_to_zero_float32: types.Bool32,
    shader_denorm_flush_to_zero_float64: types.Bool32,
    shader_rounding_mode_rte_float16: types.Bool32,
    shader_rounding_mode_rte_float32: types.Bool32,
    shader_rounding_mode_rte_float64: types.Bool32,
    shader_rounding_mode_rtz_float16: types.Bool32,
    shader_rounding_mode_rtz_float32: types.Bool32,
    shader_rounding_mode_rtz_float64: types.Bool32,
    max_update_after_bind_descriptors_in_all_pools: u32,
    shader_uniform_buffer_array_non_uniform_indexing_native: types.Bool32,
    shader_sampled_image_array_non_uniform_indexing_native: types.Bool32,
    shader_storage_buffer_array_non_uniform_indexing_native: types.Bool32,
    shader_storage_image_array_non_uniform_indexing_native: types.Bool32,
    shader_input_attachment_array_non_uniform_indexing_native: types.Bool32,
    robust_buffer_access_update_after_bind: types.Bool32,
    quad_divergent_implicit_lod: types.Bool32,
    max_per_stage_descriptor_update_after_bind_samplers: u32,
    max_per_stage_descriptor_update_after_bind_uniform_buffers: u32,
    max_per_stage_descriptor_update_after_bind_storage_buffers: u32,
    max_per_stage_descriptor_update_after_bind_sampled_images: u32,
    max_per_stage_descriptor_update_after_bind_storage_images: u32,
    max_per_stage_descriptor_update_after_bind_input_attachments: u32,
    max_descriptor_set_update_after_bind_samplers: u32,
    max_descriptor_set_update_after_bind_uniform_buffers: u32,
    max_descriptor_set_update_after_bind_uniform_buffers_dynamic: u32,
    max_descriptor_set_update_after_bind_storage_buffers: u32,
    max_descriptor_set_update_after_bind_storage_buffers_dynamic: u32,
    max_descriptor_set_update_after_bind_sampled_images: u32,
    max_descriptor_set_update_after_bind_storage_images: u32,
    max_descriptor_set_update_after_bind_input_attachments: u32,
    supported_depth_resolve_modes: types.ResolveModeFlags,
    supported_stencil_resolve_modes: types.ResolveModeFlags,
    independent_resolve_none: types.Bool32,
    independent_resolve: types.Bool32,
    filter_minmax_single_component_formats: types.Bool32,
    filter_minmax_image_component_mapping: types.Bool32,
    max_timeline_semaphore_value_difference: u64,
    framebuffer_integer_color_sample_counts: types.SampleCountFlags,
};

pub const SemaphoreTypeCreateInfo = extern struct {
    s_type: types.StructureType = .semaphore_type_create_info,
    p_next: ?*const anyopaque = null,
    semaphore_type: types.SemaphoreType,
    initial_value: u64,
};

pub const TimelineSemaphoreSubmitInfo = extern struct {
    s_type: types.StructureType = .timeline_semaphore_submit_info,
    p_next: ?*const anyopaque = null,
    wait_semaphore_value_count: u32,
    p_wait_semaphore_values: ?[*]const u64,
    signal_semaphore_value_count: u32,
    p_signal_semaphore_values: ?[*]const u64,
};

pub const SemaphoreWaitInfo = extern struct {
    s_type: types.StructureType = .semaphore_wait_info,
    p_next: ?*const anyopaque = null,
    flags: types.SemaphoreWaitFlags,
    semaphore_count: u32,
    p_semaphores: ?[*]const types.Semaphore,
    p_values: ?[*]const u64,
};

pub const SemaphoreSignalInfo = extern struct {
    s_type: types.StructureType = .semaphore_signal_info,
    p_next: ?*const anyopaque = null,
    semaphore: types.Semaphore,
    value: u64,
};
